# docker-compose.yml - Place in root directory
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - MONGODB_URL=mongodb://mongo:27017/sms_trading_bot
      - REDIS_URL=redis://redis:6379
      # Add your API keys here for local development
      # - OPENAI_API_KEY=your-key-here
      # - EODHD_API_KEY=your-key-here
      # - TWILIO_ACCOUNT_SID=your-sid-here
      # - TWILIO_AUTH_TOKEN=your-token-here
      # - TWILIO_PHONE_NUMBER=+1234567890
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sms_trading_bot

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: Redis admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

  # Optional: MongoDB admin interface  
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo

volumes:
  mongo_data:
  redis_data:
